import { Inter } from "next/font/google";
import "./globals.css";
import "./style.css";
import "./modal.css";
import "bootstrap/dist/css/bootstrap.min.css";
import NavBar from './components/navBar'
import Footer from './components/Footer'
import Line from './line/page'
import Head from 'next/head';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <meta name="keywords" content={metadata.keywords} />
        <meta property="og:title" content={metadata.title} />
        <meta property="og:description" content={metadata.description} />
        <meta property="og:image" content={metadata.image} />
        <meta property="og:url" content={metadata.canonical} />
        <meta property="og:type" content="website" />
        <meta property="og:site_name" content={metadata.name} />
        <meta property="twitter:card" content="https://www.adsdeps.com/img/ads.jpg" />
        <meta property="twitter:title" content={metadata.title} />
        <meta property="twitter:description" content={metadata.description} />
        <meta property="twitter:image" content={metadata.image} />
        <meta property="twitter:url" content={metadata.canonical} />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="canonical" href={metadata.canonical} />
      </Head>
      <body className={inter.className}>
        <NavBar />
        <Line />
        
        {children}
        <Footer />
        
      </body>
     
    </html>
  );
}
