// src/app/layout.js
import { Inter } from "next/font/google";
import "./globals.css";
import "./style.css";
import "./modal.css";
import "bootstrap/dist/css/bootstrap.min.css";
import NavBar from './components/nav';
import Footer from './components/Footer';
import Lines from './components/Lines';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        <Lines />
        {children}
        <Footer />
      </body>
    </html>
  );
}
